/*
 * STM32L552 SoC
 *
 * Copyright (c) 2023 Olof Astrand
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#ifndef HW_ARM_STM32L552_SOC_H
#define HW_ARM_STM32L552_SOC_H

#include "hw/misc/stm32f4xx_syscfg.h"
#include "hw/timer/stm32f2xx_timer.h"
#include "hw/char/stm32f2xx_usart.h"
#include "hw/adc/stm32f2xx_adc.h"
#include "hw/misc/stm32f4xx_exti.h"
#include "hw/or-irq.h"
#include "hw/ssi/stm32f2xx_spi.h"
#include "hw/arm/armv7m.h"
#include "qom/object.h"
#include "hw/arm/stm32/stm32fxxx_rcc.h"
#include "hw/arm/stm32/stm32f2xx_rtc.h"
#include "hw/arm/stm32/stm32fxxx_pwr.h"
#include "hw/arm/stm32/stm32fxxx_gpio.h"

#define TYPE_STM32L552_SOC "stm32l552-soc"
OBJECT_DECLARE_SIMPLE_TYPE(STM32L552State, STM32L552_SOC)

#define STM_NUM_USARTS 7
#define STM_NUM_TIMERS 4
#define STM_NUM_ADCS 1
#define STM_NUM_SPIS 3
#define STM_NUM_GPIO 5

#define FLASH_BASE_ADDRESS 0x08000000
#define FLASH_SIZE (1024 * 1024)
#define SRAM_BASE_ADDRESS 0x20000000
#define SRAM_SIZE (512 * 1024)
#define CCM_BASE_ADDRESS 0x10000000
#define CCM_SIZE (64 * 1024)
/*
"Name","Start","End","Length","R","W","X","Volatile","Overlay","Type","Initialized","Byte Source","Source","Comment"
"TIM2_TIM3_TIM4_TIM5_TIM6_TIM7","40000000","400017ff","0x1800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"TAMP_IWDG_SPI2_SPI3_WWDG_RTC","40002800","40003fff","0x1800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"I2C1_I2C2_I2C3_CRS_UART5_UART4_USART3_USART2","40004400","400063ff","0x2000","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"I2C4_LPUART1_LPTIM1_OPAMP_DAC_PWR","40007000","400087ff","0x1800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"LPTIM2_LPTIM3","40009400","40009bff","0x800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"FDCAN1","4000a400","4000afff","0xc00","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"USB_UCPD1","4000d400","4000dfff","0xc00","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SYSCFG_VREFBUF_COMP","40010000","400103ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SPI1_TIM1_TIM8_USART1","40012c00","40013bff","0x1000","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"TIM15_TIM16_TIM17","40014000","40014bff","0xc00","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SAI1_SAI2","40015400","40015bff","0x800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"DFSDM1","40016000","400167ff","0x800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"DMAMUX1_DMA2_DMA1","40020000","40020bff","0xc00","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"RCC","40021000","400213ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"FLASH","40022000","400223ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"CRC","40023000","400233ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"TSC","40024000","400243ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"EXTI","4002f400","4002f7ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"ICache","40030400","400307ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"GTZC_MPCBB1_GTZC_MPCBB2_GTZC_TZIC_GTZC_TZSC","40032400","400333ff","0x1000","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"GPIOA_GPIOB_GPIOC_GPIOD_GPIOE_GPIOF_GPIOG_GPIOH","42020000","42021fff","0x2000","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"ADC","42028000","420282fc","0x2fd","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"ADC_Common","42028300","420283ff","0x100","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"RNG","420c0800","420c0bff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SDMMC1","420c8000","420c83fc","0x3fd","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"FMC","44020000","440203ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"OCTOSPI1","44021000","440213ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_TIM2_SEC_TIM3_SEC_TIM4_SEC_TIM5_SEC_TIM6_SEC_TIM7","50000000","500017ff","0x1800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_TAMP_SEC_IWDG_SEC_SPI2_SEC_SPI3_SEC_WWDG_SEC_RTC","50002800","50003fff","0x1800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_I2C1_SEC_I2C2_SEC_I2C3_SEC_CRS_SEC_UART5_SEC_UART4_SEC_USART3_SEC_USART2","50004400","500063ff","0x2000","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_I2C4_SEC_LPUART1_SEC_LPTIM1_SEC_OPAMP_SEC_DAC_SEC_PWR","50007000","500087ff","0x1800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_LPTIM2_SEC_LPTIM3","50009400","50009bff","0x800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_FDCAN1","5000a400","5000afff","0xc00","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_USB_SEC_UCPD1","5000d400","5000dfff","0xc00","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_SYSCFG_SEC_VREFBUF_SEC_COMP","50010000","500103ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_SPI1_SEC_TIM1_SEC_TIM8_SEC_USART1","50012c00","50013bff","0x1000","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_TIM15_SEC_TIM16_SEC_TIM17","50014000","50014bff","0xc00","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_SAI1_SEC_SAI2","50015400","50015bff","0x800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_DFSDM1","50016000","500167ff","0x800","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_DMAMUX1_SEC_DMA2_SEC_DMA1","50020000","50020bff","0xc00","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_RCC","50021000","500213ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_FLASH","50022000","500223ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_CRC","50023000","500233ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_TSC","50024000","500243ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_EXTI","5002f400","5002f7ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_ICache","50030400","500307ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_GTZC_MPCBB1_SEC_GTZC_MPCBB2_SEC_GTZC_TZIC_SEC_GTZC_TZSC","50032400","500333ff","0x1000","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_GPIOA_SEC_GPIOB_SEC_GPIOC_SEC_GPIOD_SEC_GPIOE_SEC_GPIOF_SEC_GPIOG_SEC_GPIOH","52020000","52021fff","0x2000","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_ADC","52028000","520282fc","0x2fd","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_ADC_Common","52028300","520283ff","0x100","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_RNG","520c0800","520c0bff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_SDMMC1","520c8000","520c83fc","0x3fd","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_FMC","54020000","540203ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"SEC_OCTOSPI1","54021000","540213ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"NVIC","e000e100","e000e47c","0x37d","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"DCB","e000ee08","e000ee0c","0x5","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"NVIC_STIR","e000ef00","e000ef04","0x5","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
"DBGMCU","e0044000","e00443ff","0x400","true","true","false","true","false","Default","false","","","Generated by SVD-Loader."
*/

struct STM32L552State {
    /*< private >*/
    SysBusDevice parent_obj;
    /*< public >*/

    char *cpu_type;

    ARMv7MState armv7m;

    STM32F4xxSyscfgState syscfg;
    STM32F4xxExtiState exti;
    STM32F2XXUsartState usart[STM_NUM_USARTS];
    STM32F2XXTimerState timer[STM_NUM_TIMERS];
    OrIRQState adc_irqs;
    STM32F2XXADCState adc[STM_NUM_ADCS];
    STM32F2XXSPIState spi[STM_NUM_SPIS];
    stm32fxxx_gpio gpio[STM_NUM_GPIO];

    stm32fxxx_pwr     pwr;
    STM32FXXXRccState rcc;
    STM32F2XXRtcState rtc;

    MemoryRegion ccm;
    MemoryRegion sram;
    MemoryRegion flash;
    MemoryRegion flash_alias;

    Clock *sysclk;
    Clock *refclk;
};

#endif
